version: '3'
services:
  web:
    build: ./web/
    depends_on:
      - redis
    ports:
      - "8080:80"
    networks:
      - cache_layer
  
  redis:
    image: redis:latest
    networks:
      - cache_layer

networks:
  cache_layer :
