apiVersion: v1
kind: Service
metadata:
  name: spring-music
  labels:
    {{- include "spring.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "spring.labels" . | nindent 4 }}

